config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'

  get 'user_sessions/new'
  post 'user_sessions/create'
  get 'user_sessions/destroy'

  resources :uploads

  resources :reports

  resources :private_messages

  resources :users

end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :report
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  before_action :set_private_message, only: [:show, :edit, :update, :destroy]

  # GET /private_messages
  # GET /private_messages.json
  def index
    @private_messages = PrivateMessage.all
  end

  # GET /private_messages/1
  # GET /private_messages/1.json
  def show
  end

  # GET /private_messages/new
  def new
    @private_message = PrivateMessage.new
  end

  # GET /private_messages/1/edit
  def edit
  end

  # POST /private_messages
  # POST /private_messages.json
  def create
    @private_message = PrivateMessage.new(private_message_params)

    respond_to do |format|
      if @private_message.save
        format.html { redirect_to @private_message, notice: 'Private message was successfully created.' }
        format.json { render :show, status: :created, location: @private_message }
      else
        format.html { render :new }
        format.json { render json: @private_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /private_messages/1
  # PATCH/PUT /private_messages/1.json
  def update
    respond_to do |format|
      if @private_message.update(private_message_params)
        format.html { redirect_to @private_message, notice: 'Private message was successfully updated.' }
        format.json { render :show, status: :ok, location: @private_message }
      else
        format.html { render :edit }
        format.json { render json: @private_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private_messages/1
  # DELETE /private_messages/1.json
  def destroy
    @private_message.destroy
    respond_to do |format|
      format.html { redirect_to private_messages_url, notice: 'Private message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_message
      @private_message = PrivateMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def private_message_params
      params.require(:private_message).permit(:content, :user_id, :report_id)
    end
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/views/private_messages/_form.html.haml
= form_for @private_message do |f|
  - if @private_message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@private_message.errors.count, "error")} prohibited this private_message from being saved:"
      %ul
        - @private_message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :report_id
    = f.number_field :report_id
  .actions
    = f.submit 'Save'

app/views/private_messages/edit.html.haml
%h1 Editing private_message

= render 'form'

= link_to 'Show', @private_message
\|
= link_to 'Back', private_messages_path

app/views/private_messages/index.html.haml
%h1 Listing private_messages

%table
  %tr
    %th Content
    %th User
    %th Report
    %th
    %th
    %th

  - @private_messages.each do |private_message|
    %tr
      %td= private_message.content
      %td= private_message.user_id
      %td= private_message.report_id
      %td= link_to 'Show', private_message
      %td= link_to 'Edit', edit_private_message_path(private_message)
      %td= link_to 'Destroy', private_message, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Private message', new_private_message_path

app/views/private_messages/new.html.haml
%h1 New private_message

= render 'form'

= link_to 'Back', private_messages_path

app/views/private_messages/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @private_message.content
%p
  %b User:
  = @private_message.user_id
%p
  %b Report:
  = @private_message.report_id

= link_to 'Edit', edit_private_message_path(@private_message)
\|
= link_to 'Back', private_messages_path