config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'

  get 'user_sessions/new'
  post 'user_sessions/create'
  get 'user_sessions/destroy'

  resources :uploads

  resources :reports

  resources :private_messages

  resources :users

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  # has_attached_file :pdf,
  #                   #:styles => { :medium => "300x300>",:thumb => "100x100>" }
  #                   #:path => ":rails_root/public/:attachment/:id_partition/:style/:basename.:extension",
  #                   #:url => "/:attachment/:id_partition/:style/:basename.:extension"
  #                   :path => ":rails_root/public/:attachment/:id_partition.:extension",
  #                   :url => "/:attachment/:id_partition.:extension"
  #
  # validates_attachment :pdf,
  #                      :presence => true,
  #                      #:content_type => { :content_type => /\Aimage\/.*\Z/ },
  #                      :content_type => { :content_type => ["application/pdf"] },
  #                      :size => { :less_than => 10.megabyte }
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:pdf_file_name, :pdf_content_type, :pdf_file_size, :pdf_updated_at)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.haml
= form_for @upload do |f|
  - if @upload.errors.any?
    #error_explanation
      %h2= "#{pluralize(@upload.errors.count, "error")} prohibited this upload from being saved:"
      %ul
        - @upload.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :pdf_file_name
    = f.text_field :pdf_file_name
  .field
    = f.label :pdf_content_type
    = f.text_field :pdf_content_type
  .field
    = f.label :pdf_file_size
    = f.number_field :pdf_file_size
  .field
    = f.label :pdf_updated_at
    = f.datetime_select :pdf_updated_at
  .actions
    = f.submit 'Save'

app/views/uploads/edit.html.haml
%h1 Editing upload

= render 'form'

= link_to 'Show', @upload
\|
= link_to 'Back', uploads_path

app/views/uploads/index.html.haml
%h1 Listing uploads

%table
  %tr
    %th Pdf file name
    %th Pdf content type
    %th Pdf file size
    %th Pdf updated at
    %th
    %th
    %th

  - @uploads.each do |upload|
    %tr
      %td= upload.pdf_file_name
      %td= upload.pdf_content_type
      %td= upload.pdf_file_size
      %td= upload.pdf_updated_at
      %td= link_to 'Show', upload
      %td= link_to 'Edit', edit_upload_path(upload)
      %td= link_to 'Destroy', upload, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Upload', new_upload_path

app/views/uploads/new.html.haml
%h1 New upload

= render 'form'

= link_to 'Back', uploads_path

app/views/uploads/show.html.haml
%p#notice= notice

%p
  %b Pdf file name:
  = @upload.pdf_file_name
%p
  %b Pdf content type:
  = @upload.pdf_content_type
%p
  %b Pdf file size:
  = @upload.pdf_file_size
%p
  %b Pdf updated at:
  = @upload.pdf_updated_at

= link_to 'Edit', edit_upload_path(@upload)
\|
= link_to 'Back', uploads_path