config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'

  get 'user_sessions/new'
  post 'user_sessions/create'
  get 'user_sessions/destroy'

  resources :uploads

  resources :reports

  resources :private_messages

  resources :users

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :private_messages
  belongs_to :user
  attr_accessor :upload


  def self.search(search, user_id)
    if search
      if search == ''
        return
      else
        where("reportname like '%s'", "%#{search}%")
      end
    else
      if user_id
        where("user_id = '%i'", user_id)
      end
    end
  end

  def self.upload(upload)
    path = nil
    if  !upload.nil?
      file_name = upload.original_filename
      file = upload.read
      file_type = file_name.split('.').last
      if file_type == "pdf"
        new_name_file = Time.now.to_i
        name_folder = new_name_file
        new_file_name_with_type = "#{new_name_file}." + file_type

        #image_root = Rails.root + 'app/assets/reports/'
        image_root = "public/uploads"
        #path = image_root + "#{name_folder}/" + new_file_name_with_type
        path = image_root + "/" + new_file_name_with_type

        #Dir.mkdir(image_root + "#{name_folder}");
        #Dir.mkdir(image_root);
        File.open(path, "wb")  do |f|
          f.write(file)
        end
      else
        path = "invalid"
      end
    end

    return path
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_user
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.search(params[:search], session[:user_id])
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @private_messages = PrivateMessage.where("report_id = '%i'", params[:id])
    @private_message = PrivateMessage.new
  end

  # GET /reports/new
  def new
    @report = Report.new
    @upload = Upload.new
  end

  def newest
    @newests = Report.where("strftime('%m', 'now')- strftime('%m', created_at)   < 2")
  end

  def search
    @reports = Report.search(params[:search], nil)
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new
    @report.user_id = session[:user_id]
    #@report.report_name = params[:upload]['report_name']
    @report.report_name = report_params[:report_name]

    #save file upload
    path = Report.upload(report_params[:path])
    if !path.nil?
      if path == "invalid"
        flash[:notice] = "Pdf is invalid"
        redirect_to(:back)
        return
      else
        @report.path = path.to_s
      end
    end

    if @report.save
      redirect_to root_url
    end
    #if !path.nil?
    #@report.path = path.to_s

    #respond_to do |format|
    #if @report.save
    #render :text => "File has been uploaded successfully"
    #redirect_to root_url
    #format.html { redirect_to @report, notice: 'Report was successfully created.' }
    #format.json { render :show, status: :created, location: @report }
    #else
    #format.html { render :new }
    #format.json { render json: @report.errors, status: :unprocessable_entity }
    #end
    #end
    #else
    #render :text => "Pdf is invalid"
    #end

    # @report = Report.new(report_params)
    #
    # respond_to do |format|
    #   if @report.save
    #     format.html { redirect_to @report, notice: 'Report was successfully created.' }
    #     format.json { render :show, status: :created, location: @report }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @report.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def uploadFile
    post = Report.save(params[:upload])
    render :text => "File has been uploaded successfully"
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    @report.report_name = report_params[:report_name]
    path = Report.upload(report_params[:path])
    if !path.nil?
      if path == "invalid"
        flash[:notice] = "Pdf is invalid"
        redirect_to(:back)
        return
      else
        @report.path = path.to_s
      end
    end

    if @report.save
      redirect_to reports_url + "/" + @report.id.to_s
    end

    #respond_to do |format|
    #if @report.update(report_params)
    #format.html { redirect_to @report, notice: 'Report was successfully updated.' }
    #format.json { render :show, status: :ok, location: @report }
    #else
    #format.html { render :edit }
    #format.json { render json: @report.errors, status: :unprocessable_entity }
    #end
    #end
    # respond_to do |format|
    #   if @report.update(report_params)
    #     format.html { redirect_to @report, notice: 'Report was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @report }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @report.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def serve
    path = params[:path]
    send_file( path,
               :disposition => 'inline',
               :type => 'application/pdf',
               :x_sendfile => true )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:report_name, :path, :user_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report, html: { multipart: true, class: "dropzone"} do |f|
  .container{:style=>"background-color: #f7f7f9; margin-bottom: 20px"}
    .field
      = f.label :report_name
      = f.text_area :report_name
    .field
      = f.label "Path (only pdf format)"
      = f.file_field :path#, accept: 'image/png,image/gif,image/jpeg'
    %br
  .actions{:style=>"margin-left: 0px"}
    = f.submit "Save report", :class => "btn btn-default"
    %span.label.label-danger
      = flash[:notice]

-#= form_for @report do |f|
-#  - if @report.errors.any?
-#    #error_explanation
-#      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
-#      %ul
-#        - @report.errors.full_messages.each do |msg|
-#          %li= msg
-#
-#  .field
-#    = f.label :report_name
-#    = f.text_field :report_name
-#  .field
-#    = f.label :path
-#    = f.text_field :path
-#  .field
-#    = f.label :user_id
-#    = f.number_field :user_id
-#  .actions
-#    = f.submit 'Save'

app/views/reports/_form_mail.html.haml
%h4 New message

= form_tag :action => 'sendMail', :controller => 'emails' do
  .form-group
    %label{:for=>"email_subject"} Subject
    = text_field_tag :subject, :class => "form-control"
  %p
    %label{:for=>"email_message"} Message
    = text_area_tag  :message
  %p
    = hidden_field_tag :mail_to, params[:user_id]
  %p
    = hidden_field_tag :report_id, params[:report_id]
  %p{:style=>"margin-left: 150px"}
    = submit_tag "Send mail", :class => "btn btn-default"

.modal-header
  %button{:type=>"button", :class=>"close", "data-dismiss"=>"modal", "aria-hidden"=>"true"} ×
  %h3d#myModalLabel Modal header
.modal-body
  **here comes whatever you want to show!**
.modal-footer
  %button.btn{"data-dismiss"=>"modal", "aria-hidden"=>"true"} Close
  %button.btn.btn-primary Save changes

app/views/reports/edit.html.haml
.btn.btn-mini.btn-default.btn-xs{:style=>"float: right;"}
  = link_to 'Back', 'javascript:history.go(-1);'

%h3{:style=>"color: #337AB7"} Editing report
= render 'form'

app/views/reports/index.html.haml
.btn.btn-default{:style=>"float: right;"}
  = link_to 'New Report', new_report_path
%h3{:style=>"color: #337AB7"} My reports

%table.table.table-hover
  %thead
    %tr
      %th{:style=>"text-align: left; width: 75%;"}
        %small Reportname
      %th{:colspan=>"1", :style=>"float:right;"}
  %tbody
  - if !@reports.nil?
    - @reports.each do |report|
      %tr
        %td= report.report_name
        %td
          %a.btn.btn-mini.btn-default.btn-xs.fancybox{"data-fancybox-type"=>"iframe", :href=>'reports/serve?path='+report.path} Review
          = link_to 'Show', report, :class => 'btn btn-mini btn-default btn-xs'
          = link_to 'Edit', edit_report_path(report), :class => 'btn btn-mini btn-default btn-xs'
          = link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-default btn-xs'

app/views/reports/new.html.haml
.btn.btn-mini.btn-default.btn-xs{:style=>"float: right;"}
  = link_to 'Back', reports_path

%h4>New report

= render 'form'

app/views/reports/newest.html.haml
%h3{:style=>"color: #337AB7"} Newest reports

%table.table.table-hover
  %thead
    %tr
      %th{:style=>"text-align: left"}
        %small Reportname
      %th{:colspan=>"1"}
  %tbody
  - if !@newests.nil?
    - @newests.each do |report|
      %tr
        %td
          = report.report_name
        %td.btn.btn-mini.btn-default.btn-xs
          %a.fancybox{"data-fancybox-type"=>"iframe", :href=>'reports/serve?path='+report.path} Review
        %td.btn.btn-mini.btn-default.btn-xs
          = link_to 'Show', reports_show_path :id => report.id, :index => "newest"
        - if report.user_id == session[:user_id]
          %td.btn.btn-mini.btn-default.btn-xs
            = link_to 'Edit', edit_report_path(report)
          %td.btn.btn-mini.btn-default.btn-xs
            = link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }

app/views/reports/show.html.haml
%p#notice= notice

%p
  %b Report name:
  = @report.report_name
%p
  %b Path:
  = @report.path
%p
  %b User:
  = @report.user_id

= link_to 'Edit', edit_report_path(@report), :class => 'btn btn-mini btn-default btn-xs'
\|
= link_to 'Back', reports_path, :class => 'btn btn-mini btn-default btn-xs'